# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d990cb9fb13056dfa2e9d9573b6f857a4deafb448552d7a4c57c1908ad1f9fb06f33886dd817cd5cf5881e8b694e71b9a18989e6d1db6262b6b0e747e4872e02

test:
  secret_key_base: ee5780b94d5029df16e9de4511a64c6043c39243b78a6dce1331e77a47d28235f864d46be67c8a26babc9dd9d93e8825599e5674923090afab49abe40d8f12a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
